### ISSUE TITLE
Closing the tube?

### ISSUE THREAD

**Issue by zodiac-maniac** [csindle/ogn-hardware#1]
Hi, I like this construction and will copy it. Instead the flightaware Stick I will use another one maybe with pre-lna. Did you close the lower end of the tube? I am afraid of getting problems with insects if I let it open. Did you monitor the max temperature of this construction in summertime? I was thinking to put the most critical stuff to high temperature at the lowest point in the tube or just use a longer tube.
Did you try aluminum adhesive tape outside the tube to lower the temp inside and get lower hf noise inside the tube?
Kind regards

**Comment by csindle** [comment]
Hi,

I did not close the lower end of the tube, to allow some air circulation.
At my locations, I have found that one or two spiders a year do make it their home, but have been surprised how little debris or dust ingress there is.
On the rare summer hours that there is no wind, and the ground temperature hovers around 40℃, I have found that the Raspberry Pi does temperature-throttle, and performance is decreased (a passive heat-sink seem the obvious solution).

I would like to have more vertical airflow through the tube, but have not yet figured out how to do this simply, while still keeping out rain during 80 km/h (50 knot) winds.

Here are the CPU temperatures of one receiver (that was simultaneously doing ADS-B until 2019-06-20): 
[FAWCS](http://grafana.glidernet.org/d/000000001/receivers?var-receiver=FAWCS&orgId=1&from=now-1y&to=now)

I have not tried any of your other suggestions.

Wrapping my USB RTL SDR itself in tinfoil improved that particular device's noise floor by 3 dB.

Regarding RF noise, I suspect that most of my noise comes from inside the tube — from the Pi (although Bluetooth and WiFi is hardware disabled), or PoE electronics, etc. — or in along the Ethernet cable (from many diverse cables in the same conduit), as opposed to spurious HF picked up by the SDR.

Please let me know if you have any proven improvements.  Thanks!

**Comment by zodiac-maniac** [comment]
Hi, ok I made the same experiences.
Up to 90C is really hot. In Germany I don't find white tube but brown and grey, I hope they will bleach over the time. The most noise comes from the RPI itself so I use 0.2m usb extender to get the sdr away from the RPI. When using the POE splitter the noise explodes and I have to use wi-fi instead. I cross checked this by using the mounted SDR with a Windows to check the source of the noise. I will do a pipe construction to have an airflow, will look funny but I will try it and post a photo when finished, I thick it will withstand stronger winds. Regarding insects I will use flyprotection net inside the tubes...we'll see if that works ;-)
